// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: mitsuhitofujita/calyx/v1/auth.proto

package calyxv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LoginRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The Google-issued credential obtained by the CLI during browser sign-in.
	// Exactly one variant is expected.
	//
	// Types that are valid to be assigned to GoogleCredential:
	//
	//	*LoginRequest_IdToken
	//	*LoginRequest_AuthCode
	GoogleCredential isLoginRequest_GoogleCredential `protobuf_oneof:"google_credential"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_mitsuhitofujita_calyx_v1_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mitsuhitofujita_calyx_v1_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_mitsuhitofujita_calyx_v1_auth_proto_rawDescGZIP(), []int{0}
}

func (x *LoginRequest) GetGoogleCredential() isLoginRequest_GoogleCredential {
	if x != nil {
		return x.GoogleCredential
	}
	return nil
}

func (x *LoginRequest) GetIdToken() string {
	if x != nil {
		if x, ok := x.GoogleCredential.(*LoginRequest_IdToken); ok {
			return x.IdToken
		}
	}
	return ""
}

func (x *LoginRequest) GetAuthCode() string {
	if x != nil {
		if x, ok := x.GoogleCredential.(*LoginRequest_AuthCode); ok {
			return x.AuthCode
		}
	}
	return ""
}

type isLoginRequest_GoogleCredential interface {
	isLoginRequest_GoogleCredential()
}

type LoginRequest_IdToken struct {
	// Google OIDC ID token (JWT). Implemented in this phase.
	IdToken string `protobuf:"bytes,1,opt,name=id_token,json=idToken,proto3,oneof"`
}

type LoginRequest_AuthCode struct {
	// Google OAuth authorization code. Reserved; returns UNIMPLEMENTED for now.
	AuthCode string `protobuf:"bytes,2,opt,name=auth_code,json=authCode,proto3,oneof"`
}

func (*LoginRequest_IdToken) isLoginRequest_GoogleCredential() {}

func (*LoginRequest_AuthCode) isLoginRequest_GoogleCredential() {}

type LoginResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The Calyx-issued session token (JWT) to be sent on subsequent requests.
	SessionToken string `protobuf:"bytes,1,opt,name=session_token,json=sessionToken,proto3" json:"session_token,omitempty"`
	// When the session token expires.
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_mitsuhitofujita_calyx_v1_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mitsuhitofujita_calyx_v1_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_mitsuhitofujita_calyx_v1_auth_proto_rawDescGZIP(), []int{1}
}

func (x *LoginResponse) GetSessionToken() string {
	if x != nil {
		return x.SessionToken
	}
	return ""
}

func (x *LoginResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

var File_mitsuhitofujita_calyx_v1_auth_proto protoreflect.FileDescriptor

const file_mitsuhitofujita_calyx_v1_auth_proto_rawDesc = "" +
	"\n" +
	"#mitsuhitofujita/calyx/v1/auth.proto\x12\x18mitsuhitofujita.calyx.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"_\n" +
	"\fLoginRequest\x12\x1b\n" +
	"\bid_token\x18\x01 \x01(\tH\x00R\aidToken\x12\x1d\n" +
	"\tauth_code\x18\x02 \x01(\tH\x00R\bauthCodeB\x13\n" +
	"\x11google_credential\"o\n" +
	"\rLoginResponse\x12#\n" +
	"\rsession_token\x18\x01 \x01(\tR\fsessionToken\x129\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt2g\n" +
	"\vAuthService\x12X\n" +
	"\x05Login\x12&.mitsuhitofujita.calyx.v1.LoginRequest\x1a'.mitsuhitofujita.calyx.v1.LoginResponseBPZNgithub.com/mitsuhitofujita/calyx/shared/proto/mitsuhitofujita/calyx/v1;calyxv1b\x06proto3"

var (
	file_mitsuhitofujita_calyx_v1_auth_proto_rawDescOnce sync.Once
	file_mitsuhitofujita_calyx_v1_auth_proto_rawDescData []byte
)

func file_mitsuhitofujita_calyx_v1_auth_proto_rawDescGZIP() []byte {
	file_mitsuhitofujita_calyx_v1_auth_proto_rawDescOnce.Do(func() {
		file_mitsuhitofujita_calyx_v1_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mitsuhitofujita_calyx_v1_auth_proto_rawDesc), len(file_mitsuhitofujita_calyx_v1_auth_proto_rawDesc)))
	})
	return file_mitsuhitofujita_calyx_v1_auth_proto_rawDescData
}

var file_mitsuhitofujita_calyx_v1_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_mitsuhitofujita_calyx_v1_auth_proto_goTypes = []any{
	(*LoginRequest)(nil),          // 0: mitsuhitofujita.calyx.v1.LoginRequest
	(*LoginResponse)(nil),         // 1: mitsuhitofujita.calyx.v1.LoginResponse
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_mitsuhitofujita_calyx_v1_auth_proto_depIdxs = []int32{
	2, // 0: mitsuhitofujita.calyx.v1.LoginResponse.expires_at:type_name -> google.protobuf.Timestamp
	0, // 1: mitsuhitofujita.calyx.v1.AuthService.Login:input_type -> mitsuhitofujita.calyx.v1.LoginRequest
	1, // 2: mitsuhitofujita.calyx.v1.AuthService.Login:output_type -> mitsuhitofujita.calyx.v1.LoginResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_mitsuhitofujita_calyx_v1_auth_proto_init() }
func file_mitsuhitofujita_calyx_v1_auth_proto_init() {
	if File_mitsuhitofujita_calyx_v1_auth_proto != nil {
		return
	}
	file_mitsuhitofujita_calyx_v1_auth_proto_msgTypes[0].OneofWrappers = []any{
		(*LoginRequest_IdToken)(nil),
		(*LoginRequest_AuthCode)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mitsuhitofujita_calyx_v1_auth_proto_rawDesc), len(file_mitsuhitofujita_calyx_v1_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mitsuhitofujita_calyx_v1_auth_proto_goTypes,
		DependencyIndexes: file_mitsuhitofujita_calyx_v1_auth_proto_depIdxs,
		MessageInfos:      file_mitsuhitofujita_calyx_v1_auth_proto_msgTypes,
	}.Build()
	File_mitsuhitofujita_calyx_v1_auth_proto = out.File
	file_mitsuhitofujita_calyx_v1_auth_proto_goTypes = nil
	file_mitsuhitofujita_calyx_v1_auth_proto_depIdxs = nil
}
